extra-experimental-features = nix-command flakes

# Honoured by the daemon only for trusted users; init.sh adds the current user.
extra-substituters = https://mirrors.ustc.edu.cn/nix-channels/store?priority=10 https://nix-community.cachix.org
extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
